### PR TITLE
Replace file reads and writes utilizing Path (fixes #8)

### LINKED ISSUE #8: PyPy3 tests fail with ZEO 6.0
### What I did:

GHA is running the tests for PyPy3 and fails since using ZEO 6.0.0.

### What I expect to happen:

Successful tests.

### What actually happened:

Failures in strange ways, see https://github.com/zopefoundation/zc.zodbrecipes/actions/runs/6995392867/job/19045169682

### What version of Python and Zope/Addons I am using:

* PyPy3
* `master` branch of `zc.zodbrecipes`.

Sorry for the broad CC but this package is not listed as maintained, so I do not know if it is still actually used.
@zopefoundation/developers Is anyone interested in fixing this issue? Otherwise I'd drop PyPy3 support.

### PR DESCRIPTION
**Pull request by jan-jockusch**
I rather stupidly followed the suggestions made by @leorochael in this PR, just to help out a bit.

### CODE REVIEW

**Review by dataflake — APPROVED** [review]

**Review by d-maurer — APPROVED** [review]
Maybe: add a `CHANGES.rst` entry describing the change with reference to the fixed issue.

**Comment by jan-jockusch** [comment]
> Maybe: add a `CHANGES.rst` entry describing the change with reference to the fixed issue.

Thanks, reviewers! I'll add the missing entry pronto.

**Comment by jan-jockusch** [comment]
> @jan-jockusch In case you're not aware, the PR author - you - does the final merge when the prerequisites like passing tests and reviewer approval are met.

Thanks for the reminder! Yes, I thought that's the rule and was about to, but I wanted to make sure I don't trespass and was therefore looking for docs to confirm I have the green light. It's been a while since I last contributed…

**Comment by dataflake** [comment]
Great, thanks for the PR!

**Pull request merged**
